
server:
  port: 8080
spring:
  application:
    name: api-gateway
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      enabled: true
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${CONFIG_DB_URL}
    username: ${config.dbUser}
    password: ${config.dbPassword}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

niws:
  loadbalancer:
    availabilityFilteringRule:
      activeConnectionsLimit: 2147483647

zuul:
  ssl-hostname-validation-enabled: false
  host:
    time-to-live: -1
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000
    sensitiveHeaders: Cookie,Set-Cookie
    
ribbon:
  okhttp:
    enabled: true
    
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 200000