export class FarmerLeads {
    // id: string;
    // stateName : string;
    // districtName : string;
    // tehsilName : string;
    // villageName : string;
    // primaryMobile : string;
    // primaryMobileType : string;
    // secondaryMobile : string;
    // secondaryMobileType : string;
    // farmerSalutation : string;
    // farmerName : string;
    // fatherName : string;
    // husbandName : string;
    // referenceName : string;
    // referenceMobile : string;
    // ownLand : string;
    // ownLandSize : number;
    // farmSize : number;
    // irrigatedLand : string;
    // irrigatedLandSize : number;
    // willingnessToJoinUs : string;
    // isVip : string;
    // vipDesignation : string;
    // vipStatus : string;
    // prScoutId : number;
    // status : string;
    // latitude : number;
    // longitude : number;
    uuId: string;
    farmerName: string;
    referenceName: string;
    referenceMobile: string;
    ownLandSize: number;
    irrigatedLandSize: number;
    vipDesignation: string;
    vipStatus: string;
    govtProof: string;
    language: string;

}