package com.krishi.model;

public enum MasterDataTable {

	STATE, EDUCATION_TYPE, DISTRICT, COMMODITY, FERTILIZER_APPLICATION_METHOD, GOVT_OFFICIAL_DEPT, INSURANCE_COMPANY,
	IRRIGATION_METHOD, IRRIGATION_SOURCE, LANGUAGE, POI_TYPE, REGION, RESIDUE_DISPOSE_TYPE, SEASON, SEED_SOURCE,
	UNIT_OF_MEASUREMENT, MACHINERY, LOAN_SOURCE, LOAN_PURPOSE, KYC_DOC_TYPE, GOVT_OFFICIAL_DESIGNATION, TEHSIL,
	STATE_LANGUAGE,
	/* STATE_SEASON, */ STRESS_TYPE, PHENOPHASE, AGROCHEMICAL, VILLAGE, AGROCHEMICAL_COMPANY,
	AGROCHEMICAL_TYPE, PANCHAYAT, AGROCHEMICAL_BRAND, PESTICIDES, ENROLLMENT_PLACE, FERTILIZER, MOBILE_TYPE,
	PHENOPHASE_DURATION, PLANT_PART, PROXY_RELATION_TYPE, SEED_TREATMENT_AGENT, STRESS, STRESS_SYMPTOMS, VARIETY,
	VIP_STATUS, STRESS_CONTROL_MEASURES, STRESS_SEVERITY_CONTROL_MEASURES, STRESS_SEVERITY, VIP_DESIGNATION,
	STRESS_RECOMMENDATION, HEALTH_QUESTIONNAIRE, TILE_ZL11,
	/* STATE_SEASON_COMMODITY, */ MBEP, VARIETY_QUALITY,
	/* REGIONAL_VARIETY, */CALLING_STATUS,GENERAL_BANK,
	GENERAL_BANK_BRANCH,ALLIED_ACTIVITY,REGIONAL_MONTHLY_WEATHER_BASED_TRAVEL_TIME,VILLAGE_TO_RL_DISTANCE,
	WEATHER_BASED_TRAVEL_TIME,TASK_TYPE_SPECIFICATIONS,GENERAL_TERRAIN_TYPE,REGIONAL_CONNECTIVITY_TIME,VILLAGE_TO_VILLAGE_DISTANCE,
	CROPDATA_CALENDER , HS_CODE , STANDARD_QUANTITY_CHART,LH_WAREHOUSE,PACKAGING_TYPE,QUALITY_PARAMETERE,QUALITY_COMMODITY_PARAMETERE,
	REGIONAL_COMMODITY
	

}
