export const globalConstants = {

    deleteDataTitle: 'Delete Confirmation ',
    deleteDataMsg: 'Are you sure to Delete ',
    approveDataTitle: 'Approve Confirmation ',
    approveDataMsg: 'Are you sure to Approve ',
    finalizeDataTitle: 'Finalize Confirmation ',
    finalizeDataMsg: 'Are you sure to Finalize ',
    rejectDataTitle: 'Reject Confirmation ',
    notFoundDataTitle: 'Not Found Confirmation ',
    rejectDataMsg: 'Are you sure to Reject ',
    closeDataTitle: 'Close Confirmation ',
    closeDataMsg: 'Are you sure to Close ',
    activeDataTitle: 'Activate Confirmation ',
    activeDataMsg: 'Are you sure to Activate ',
    deactiveDataTitle: 'Deactivate Confirmation ',
    deactiveDataMsg: 'Are you sure to Deactivate ',
    shortlistDataTitle: 'Shortlist Confirmation ',
    shortlistDataMsg: 'Are you sure to Shortlist ',
    holdDataTitle: 'Hold Confirmation ',
    holdDataMsg: 'Are you sure to Hold ',
    interviewScheduleDataTitle: 'Interview Schedule Confirmation ',
    interviewScheduleDataMsg: 'Are you sure to Schedule Interview for ',
    selectDataTitle: 'Select Confirmation ',
    selectDataMsg: 'Are you sure to Select ',
    reActiveDataTitle: 'Re-Activate Confirmation ',
    reActiveDataMsg: 'Are you sure to Re-Activate ',
    completedDataTitle: 'Complete Confirmation ',
    completedDataMsg: 'Are you sure to mark as Complete ',
    ID: 'id',
    STATUS: 'status',
    NAME: 'name',
    DOCUMENT_NAME: 'documentName',
    INACTIVE_STATUS: 'Inactive',
    ACTIVE_STATUS: 'Active',
    APPROVED_STATUS: 'Approved',
    REJECTED_STATUS: 'Rejected',
    DELETED_STATUS: 'Deleted',
    CLOSED_STATUS: 'Closed',
    DEACTIVE_STATUS: 'Deactive',
    SHORTLISTED_STATUS: 'Shortlisted',
    HOLD_STATUS: 'Hold',
    INTERVIEW_SCHEDULED_STATUS: 'Interview Scheduled',
    SELECTED_STATUS: 'Selected',
    CAN_NOT_FINALIZE: 'You Can Not Finalize This Record As It Is Not Approved',
    NOT_FOUND: 'Are You Sure This Entry Is Not Found?',
    EXPIRED_STATUS: 'Expired',
    APPLICATION_TYPE: 'Franchise'
}
